from django.core.management import BaseCommand

from prison.models import *

from prison.views import Wardens


class Command(BaseCommand):
    def handle(self, *args, **options):
        Wardens = [{"FirstName":"Annadiana","LastName":"Elspeth","Email":"edacca0@topsy.com","ServiceNumber":23,"Gender":"Female","Age":81,"Weight":31},
{"FirstName":"Cristine","LastName":"Ingaborg","Email":"igianelli1@fda.gov","ServiceNumber":61,"Gender":"Female","Age":39,"Weight":28},
{"FirstName":"Colet","LastName":"Corey","Email":"cbiagi2@spiegel.de","ServiceNumber":84,"Gender":"Male","Age":67,"Weight":85},
{"FirstName":"Terrill","LastName":"Kincaid","Email":"kstaves3@tripod.com","ServiceNumber":68,"Gender":"Male","Age":40,"Weight":42},
{"FirstName":"Hurlee","LastName":"Harwell","Email":"hokey4@t-online.de","ServiceNumber":12,"Gender":"Male","Age":100,"Weight":5},
{"FirstName":"Brice","LastName":"Roddy","Email":"rrossborough5@bloglines.com","ServiceNumber":47,"Gender":"Male","Age":1,"Weight":35},
{"FirstName":"Raymund","LastName":"Godart","Email":"gmachen6@sphinn.com","ServiceNumber":35,"Gender":"Male","Age":22,"Weight":79},
{"FirstName":"Vicki","LastName":"Abigail","Email":"akyteley7@businesswire.com","ServiceNumber":59,"Gender":"Female","Age":2,"Weight":67},
{"FirstName":"Cyrillus","LastName":"Arthur","Email":"arook8@mapquest.com","ServiceNumber":92,"Gender":"Male","Age":14,"Weight":59},
{"FirstName":"Audrie","LastName":"Jo-ann","Email":"jspittles9@yandex.ru","ServiceNumber":55,"Gender":"Female","Age":61,"Weight":63},
{"FirstName":"Callida","LastName":"Nevsa","Email":"noddea@narod.ru","ServiceNumber":80,"Gender":"Female","Age":75,"Weight":41},
{"FirstName":"Carmelia","LastName":"Babette","Email":"bfarrynb@tripod.com","ServiceNumber":10,"Gender":"Female","Age":60,"Weight":93},
{"FirstName":"Eward","LastName":"Somerset","Email":"slemarc@buzzfeed.com","ServiceNumber":11,"Gender":"Male","Age":10,"Weight":17},
{"FirstName":"Bendick","LastName":"Ham","Email":"hrummind@friendfeed.com","ServiceNumber":40,"Gender":"Male","Age":24,"Weight":19},
{"FirstName":"Merilee","LastName":"Crystal","Email":"ccolcombe@arstechnica.com","ServiceNumber":24,"Gender":"Female","Age":3,"Weight":79},
{"FirstName":"Grantham","LastName":"Gearalt","Email":"gbeushawf@github.io","ServiceNumber":60,"Gender":"Male","Age":10,"Weight":92},
{"FirstName":"Kory","LastName":"Merry","Email":"mboullerg@desdev.cn","ServiceNumber":86,"Gender":"Male","Age":15,"Weight":2},
{"FirstName":"Brnaba","LastName":"Flem","Email":"fdorkingh@addthis.com","ServiceNumber":98,"Gender":"Male","Age":87,"Weight":59},
{"FirstName":"Amy","LastName":"Karin","Email":"kbruggemani@ocn.ne.jp","ServiceNumber":90,"Gender":"Female","Age":69,"Weight":79},
{"FirstName":"Doroteya","LastName":"Lila","Email":"lwheatcroftj@ask.com","ServiceNumber":65,"Gender":"Female","Age":61,"Weight":100},
{"FirstName":"Hally","LastName":"Janet","Email":"jvanrembrandtk@opera.com","ServiceNumber":65,"Gender":"Female","Age":54,"Weight":48},
{"FirstName":"Dianemarie","LastName":"Jeannine","Email":"jmallinarl@unc.edu","ServiceNumber":69,"Gender":"Female","Age":99,"Weight":4},
{"FirstName":"Rolland","LastName":"Matthieu","Email":"mcrookshankm@stanford.edu","ServiceNumber":1,"Gender":"Male","Age":75,"Weight":6},
{"FirstName":"Winn","LastName":"Bax","Email":"biacovonen@pcworld.com","ServiceNumber":2,"Gender":"Male","Age":55,"Weight":7},
{"FirstName":"Renata","LastName":"Ira","Email":"icolebourno@yahoo.co.jp","ServiceNumber":90,"Gender":"Female","Age":11,"Weight":94},
{"FirstName":"Zeb","LastName":"Trever","Email":"tickowicsp@seattletimes.com","ServiceNumber":57,"Gender":"Male","Age":17,"Weight":86},
{"FirstName":"Eugen","LastName":"Luther","Email":"lgrassickq@squidoo.com","ServiceNumber":22,"Gender":"Male","Age":4,"Weight":78},
{"FirstName":"Genia","LastName":"Kikelia","Email":"kcailr@apache.org","ServiceNumber":74,"Gender":"Female","Age":9,"Weight":95},
{"FirstName":"Lorene","LastName":"Candie","Email":"ccobbledicks@topsy.com","ServiceNumber":76,"Gender":"Female","Age":29,"Weight":64},
{"FirstName":"Marietta","LastName":"Glen","Email":"gstallent@reuters.com","ServiceNumber":47,"Gender":"Male","Age":24,"Weight":81},
{"FirstName":"Lizzy","LastName":"Ingeborg","Email":"ioholleganu@goo.gl","ServiceNumber":17,"Gender":"Female","Age":53,"Weight":58},
{"FirstName":"Deck","LastName":"Hirsch","Email":"hpedrickv@toplist.cz","ServiceNumber":28,"Gender":"Male","Age":54,"Weight":74},
{"FirstName":"Krissy","LastName":"Gaylene","Email":"ggurgew@netscape.com","ServiceNumber":30,"Gender":"Female","Age":32,"Weight":22},
{"FirstName":"Aubrette","LastName":"Cordelie","Email":"cbucknerx@jigsy.com","ServiceNumber":61,"Gender":"Female","Age":89,"Weight":71},
{"FirstName":"Yvette","LastName":"Elianore","Email":"ekleeweiny@google.es","ServiceNumber":14,"Gender":"Female","Age":49,"Weight":90},
{"FirstName":"Dun","LastName":"Darrel","Email":"dbrewittz@imgur.com","ServiceNumber":85,"Gender":"Male","Age":37,"Weight":1},
{"FirstName":"Elga","LastName":"Betty","Email":"bdampney10@engadget.com","ServiceNumber":17,"Gender":"Female","Age":11,"Weight":77},
{"FirstName":"Sidnee","LastName":"Engelbert","Email":"edeanesy11@epa.gov","ServiceNumber":50,"Gender":"Male","Age":79,"Weight":52},
{"FirstName":"Fallon","LastName":"Heidie","Email":"hvesco12@google.pl","ServiceNumber":67,"Gender":"Female","Age":37,"Weight":92},
{"FirstName":"Melitta","LastName":"Ashleigh","Email":"avint13@drupal.org","ServiceNumber":8,"Gender":"Female","Age":83,"Weight":98},
{"FirstName":"Mureil","LastName":"Fredra","Email":"fdobbs14@quantcast.com","ServiceNumber":6,"Gender":"Female","Age":53,"Weight":13},
{"FirstName":"Alphard","LastName":"Curcio","Email":"cmazillius15@fda.gov","ServiceNumber":19,"Gender":"Male","Age":78,"Weight":94},
{"FirstName":"Dreddy","LastName":"Maribeth","Email":"mcrutchfield16@theguardian.com","ServiceNumber":48,"Gender":"Female","Age":17,"Weight":8},
{"FirstName":"Ranna","LastName":"Katharine","Email":"ksutor17@multiply.com","ServiceNumber":36,"Gender":"Female","Age":86,"Weight":35},
{"FirstName":"Wynnie","LastName":"Dulcea","Email":"dpartridge18@soundcloud.com","ServiceNumber":63,"Gender":"Female","Age":67,"Weight":19},
{"FirstName":"Tann","LastName":"Winthrop","Email":"wblenkinsop19@webs.com","ServiceNumber":9,"Gender":"Male","Age":18,"Weight":23},
{"FirstName":"Dorie","LastName":"Tobit","Email":"tubee1a@w3.org","ServiceNumber":72,"Gender":"Male","Age":76,"Weight":30},
{"FirstName":"Roosevelt","LastName":"Keary","Email":"kbradley1b@phpbb.com","ServiceNumber":62,"Gender":"Male","Age":2,"Weight":94},
{"FirstName":"Almeda","LastName":"Caitlin","Email":"ckemson1c@princeton.edu","ServiceNumber":49,"Gender":"Female","Age":14,"Weight":8},
{"FirstName":"Bartram","LastName":"Barret","Email":"broelofs1d@wufoo.com","ServiceNumber":98,"Gender":"Male","Age":2,"Weight":77},
{"FirstName":"Pamelina","LastName":"Lusa","Email":"ljennings1e@nasa.gov","ServiceNumber":63,"Gender":"Female","Age":31,"Weight":9},
{"FirstName":"Aldis","LastName":"Carolus","Email":"cdalgliesh1f@jiathis.com","ServiceNumber":84,"Gender":"Male","Age":50,"Weight":52},
{"FirstName":"Richmound","LastName":"Immanuel","Email":"ibaudinot1g@boston.com","ServiceNumber":21,"Gender":"Male","Age":68,"Weight":81},
{"FirstName":"Adlai","LastName":"Gualterio","Email":"gbotterill1h@nba.com","ServiceNumber":75,"Gender":"Male","Age":47,"Weight":58},
{"FirstName":"Patrizia","LastName":"Jordanna","Email":"jgalland1i@lycos.com","ServiceNumber":39,"Gender":"Female","Age":44,"Weight":3},
{"FirstName":"Phip","LastName":"Morly","Email":"msmallacombe1j@seesaa.net","ServiceNumber":10,"Gender":"Male","Age":23,"Weight":63},
{"FirstName":"Harbert","LastName":"Ned","Email":"ntriplett1k@cyberchimps.com","ServiceNumber":54,"Gender":"Male","Age":97,"Weight":60},
{"FirstName":"Rosemonde","LastName":"Zelma","Email":"zsokale1l@ca.gov","ServiceNumber":77,"Gender":"Female","Age":14,"Weight":59},
{"FirstName":"Allistir","LastName":"Truman","Email":"tohdirscoll1m@youku.com","ServiceNumber":89,"Gender":"Male","Age":42,"Weight":87},
{"FirstName":"Abbie","LastName":"Thom","Email":"taldus1n@themeforest.net","ServiceNumber":77,"Gender":"Male","Age":45,"Weight":39},
{"FirstName":"Giffie","LastName":"Hewet","Email":"hhamblyn1o@jiathis.com","ServiceNumber":32,"Gender":"Male","Age":8,"Weight":14},
{"FirstName":"Paige","LastName":"Claudianus","Email":"cheakey1p@harvard.edu","ServiceNumber":43,"Gender":"Male","Age":37,"Weight":19},
{"FirstName":"Golda","LastName":"Rhianon","Email":"rnorbury1q@parallels.com","ServiceNumber":70,"Gender":"Female","Age":28,"Weight":53},
{"FirstName":"Nichols","LastName":"Renault","Email":"rleedal1r@about.com","ServiceNumber":55,"Gender":"Male","Age":80,"Weight":74},
{"FirstName":"Karylin","LastName":"Beckie","Email":"biddens1s@loc.gov","ServiceNumber":72,"Gender":"Female","Age":27,"Weight":56},
{"FirstName":"Howie","LastName":"Zed","Email":"zpaish1t@indiegogo.com","ServiceNumber":21,"Gender":"Male","Age":90,"Weight":16},
{"FirstName":"Ingra","LastName":"Arlen","Email":"abrolan1u@earthlink.net","ServiceNumber":8,"Gender":"Male","Age":76,"Weight":40},
{"FirstName":"Thebault","LastName":"Abie","Email":"adungay1v@booking.com","ServiceNumber":25,"Gender":"Male","Age":89,"Weight":33},
{"FirstName":"Grier","LastName":"Estrella","Email":"ekobelt1w@bloglovin.com","ServiceNumber":56,"Gender":"Female","Age":73,"Weight":5},
{"FirstName":"Guss","LastName":"Ellary","Email":"ecottesford1x@newyorker.com","ServiceNumber":85,"Gender":"Male","Age":4,"Weight":96},
{"FirstName":"Gael","LastName":"Felipe","Email":"flomansey1y@webeden.co.uk","ServiceNumber":65,"Gender":"Male","Age":93,"Weight":69},
{"FirstName":"Adela","LastName":"Kittie","Email":"kartois1z@myspace.com","ServiceNumber":67,"Gender":"Female","Age":36,"Weight":30},
{"FirstName":"Cosmo","LastName":"Walton","Email":"wwatchorn20@paginegialle.it","ServiceNumber":57,"Gender":"Male","Age":65,"Weight":76},
{"FirstName":"Esmaria","LastName":"Yettie","Email":"yfoggarty21@bizjournals.com","ServiceNumber":79,"Gender":"Female","Age":30,"Weight":17},
{"FirstName":"Craggy","LastName":"Thane","Email":"twhiffin22@timesonline.co.uk","ServiceNumber":68,"Gender":"Male","Age":91,"Weight":97},
{"FirstName":"Ogdon","LastName":"Stearne","Email":"sspringett23@list-manage.com","ServiceNumber":51,"Gender":"Male","Age":38,"Weight":17},
{"FirstName":"Nicolea","LastName":"Dayle","Email":"djablonski24@myspace.com","ServiceNumber":75,"Gender":"Female","Age":95,"Weight":50},
{"FirstName":"Kit","LastName":"Tammie","Email":"tjanaud25@gravatar.com","ServiceNumber":46,"Gender":"Female","Age":16,"Weight":76},
{"FirstName":"Timoteo","LastName":"Geoffrey","Email":"gbezant26@phpbb.com","ServiceNumber":53,"Gender":"Male","Age":41,"Weight":22},
{"FirstName":"Colly","LastName":"Cloris","Email":"csutherland27@narod.ru","ServiceNumber":70,"Gender":"Female","Age":27,"Weight":21},
{"FirstName":"Teodorico","LastName":"Jerrie","Email":"jdoulton28@people.com.cn","ServiceNumber":25,"Gender":"Male","Age":98,"Weight":4},
{"FirstName":"Kynthia","LastName":"Ardra","Email":"abursnoll29@jigsy.com","ServiceNumber":92,"Gender":"Female","Age":62,"Weight":94},
{"FirstName":"Kary","LastName":"Eartha","Email":"eemeney2a@geocities.jp","ServiceNumber":8,"Gender":"Female","Age":70,"Weight":17},
{"FirstName":"Helen","LastName":"Clarey","Email":"ctomley2b@webmd.com","ServiceNumber":90,"Gender":"Female","Age":91,"Weight":71},
{"FirstName":"Alexandros","LastName":"Irvin","Email":"iwolfendale2c@admin.ch","ServiceNumber":48,"Gender":"Male","Age":18,"Weight":74},
{"FirstName":"Zola","LastName":"Maxi","Email":"mpapworth2d@nasa.gov","ServiceNumber":46,"Gender":"Female","Age":76,"Weight":75},
{"FirstName":"Tori","LastName":"Christy","Email":"cpallent2e@wunderground.com","ServiceNumber":21,"Gender":"Female","Age":55,"Weight":96},
{"FirstName":"Herve","LastName":"Garry","Email":"gseignior2f@youtu.be","ServiceNumber":23,"Gender":"Male","Age":71,"Weight":59},
{"FirstName":"Jaquenette","LastName":"Jessalin","Email":"jgalsworthy2g@typepad.com","ServiceNumber":23,"Gender":"Female","Age":26,"Weight":2},
{"FirstName":"Prescott","LastName":"Filberto","Email":"fcoultard2h@bing.com","ServiceNumber":28,"Gender":"Male","Age":84,"Weight":20},
{"FirstName":"Gualterio","LastName":"Darrin","Email":"dbumpass2i@google.fr","ServiceNumber":23,"Gender":"Male","Age":37,"Weight":81},
{"FirstName":"Jaquenetta","LastName":"Marlane","Email":"mduffree2j@thetimes.co.uk","ServiceNumber":43,"Gender":"Female","Age":69,"Weight":50},
{"FirstName":"Sutherlan","LastName":"Morey","Email":"mmcnamara2k@simplemachines.org","ServiceNumber":80,"Gender":"Male","Age":99,"Weight":70},
{"FirstName":"Skipton","LastName":"Simon","Email":"ssimms2l@biglobe.ne.jp","ServiceNumber":97,"Gender":"Male","Age":43,"Weight":96},
{"FirstName":"Shaine","LastName":"Ulrick","Email":"upyer2m@oakley.com","ServiceNumber":33,"Gender":"Male","Age":51,"Weight":32},
{"FirstName":"Merry","LastName":"Mareah","Email":"mesposi2n@technorati.com","ServiceNumber":23,"Gender":"Female","Age":65,"Weight":9},
{"FirstName":"Rufe","LastName":"Munmro","Email":"msoppit2o@dot.gov","ServiceNumber":3,"Gender":"Male","Age":38,"Weight":96},
{"FirstName":"Harwilll","LastName":"Elmer","Email":"eadam2p@ebay.co.uk","ServiceNumber":53,"Gender":"Male","Age":25,"Weight":3},
{"FirstName":"Renard","LastName":"Hanson","Email":"hstedson2q@state.gov","ServiceNumber":48,"Gender":"Male","Age":53,"Weight":41},
{"FirstName":"Bradan","LastName":"Benedict","Email":"bgillard2r@yahoo.co.jp","ServiceNumber":95,"Gender":"Male","Age":92,"Weight":90}]
        for w in Wardens:
            warden = Warden(**w)
            warden.save()
        print("Populated Wardens successfully")
        # python manage.py populate
