# Generated by Django 5.1.3 on 2024-11-25 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Dob', models.DateField()),
                ('Gender', models.CharField(max_length=10)),
                ('Weight', models.PositiveIntegerField(default=0)),
                ('PhoneNUmber', models.PositiveIntegerField(default=0)),
                ('ServiceNumber', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Wardens',
            },
        ),
        migrations.CreateModel(
            name='Armoury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GunModel', models.CharField(max_length=10)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Warden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prison.warden')),
            ],
            options={
                'db_table': 'Armoury',
            },
        ),
    ]
