# Generated by Django 5.1.3 on 2024-11-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0002_remove_warden_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warden',
            name='Dob',
        ),
        migrations.AddField(
            model_name='warden',
            name='Age',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
