# Generated by Django 5.1.3 on 2024-11-26 10:18

import prison.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0003_remove_warden_dob_warden_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='warden',
            name='ProfilePicture',
            field=models.ImageField(null=True, upload_to=prison.models.generate_unique_name),
        ),
    ]
