# Generated by Django 5.1.3 on 2024-11-27 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0004_warden_profilepicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armoury',
            name='status',
        ),
    ]
