# Generated by Django 5.1.3 on 2024-11-27 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0005_remove_armoury_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='armoury',
            table='armoury',
        ),
    ]
