# Generated by Django 5.1.3 on 2024-11-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0006_alter_armoury_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='armoury',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
