# Generated by Django 5.1.3 on 2024-12-08 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0007_armoury_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issuing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('expected_return_date', models.DateField()),
                ('return_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Gun', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prison.armoury')),
            ],
            options={
                'verbose_name': 'Issuing',
                'verbose_name_plural': 'Issuings',
                'db_table': 'issuing',
                'ordering': ('status', 'expected_return_date'),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_request_id', models.CharField(max_length=100)),
                ('checkout_request_id', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issuing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prison.issuing')),
            ],
        ),
    ]
